"""photo model fix

Revision ID: 308b18df3b50
Revises: 03910f44f07f
Create Date: 2026-02-09 12:46:31.453306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308b18df3b50'
down_revision: Union[str, Sequence[str], None] = '03910f44f07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
