"""cascade cleanup

Revision ID: 677ad34f29cb
Revises: 3f07d5a59d93
Create Date: 2026-02-07 16:33:37.990372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677ad34f29cb'
down_revision: Union[str, Sequence[str], None] = '3f07d5a59d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.CheckConstraint('value BETWEEN 1 AND 5', name='ck_rating_value_range'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'user_id', name='uix_rating_photo_user')
    )
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_photo_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('photo_tags_photo_id_fkey'), 'photo_tags', type_='foreignkey')
    op.drop_constraint(op.f('photo_tags_tag_id_fkey'), 'photo_tags', type_='foreignkey')
    op.create_foreign_key(None, 'photo_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'photo_tags', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.add_column('photos', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('photos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('public_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('public_links_transformed_image_id_fkey'), 'public_links', type_='foreignkey')
    op.create_foreign_key(None, 'public_links', 'transformed_images', ['transformed_image_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transformed_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('transformed_images_photo_id_fkey'), 'transformed_images', type_='foreignkey')
    op.create_foreign_key(None, 'transformed_images', 'photos', ['photo_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'transformed_images', type_='foreignkey')
    op.create_foreign_key(op.f('transformed_images_photo_id_fkey'), 'transformed_images', 'photos', ['photo_id'], ['id'])
    op.alter_column('transformed_images', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'public_links', type_='foreignkey')
    op.create_foreign_key(op.f('public_links_transformed_image_id_fkey'), 'public_links', 'transformed_images', ['transformed_image_id'], ['id'])
    op.alter_column('public_links', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('photos', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('photos', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('photos', 'cloudinary_public_id')
    op.drop_constraint(None, 'photo_tags', type_='foreignkey')
    op.drop_constraint(None, 'photo_tags', type_='foreignkey')
    op.create_foreign_key(op.f('photo_tags_tag_id_fkey'), 'photo_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('photo_tags_photo_id_fkey'), 'photo_tags', 'photos', ['photo_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_photo_id_fkey'), 'comments', 'photos', ['photo_id'], ['id'])
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'])
    op.alter_column('comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table('ratings')
    # ### end Alembic commands ###
